### ISSUE TITLE
Running in Standalone Cluster

### ISSUE THREAD

**Issue by adschwartz** [ariskk/flink4s#20]
Thanks for starting this work @ariskk! I've been working on a project where I'd like to have 2.13 compatibility and found this project useful and would like to contribute as well. Flink retiring their scala lib is the right approach imo. I also use Cats and would like to leverage that as much as possible and having libraries that wrap java Flink is the way to go.

I've been able to get a simple job (using this project) running in a local session (i.e. a Flink minicluster). However, once I try and run it in a standalone cluster things break down, due to the standalone cluster being built with 2.12 and my jar being built with 2.13. Do we need to build the standalone cluster with 2.13 as well or is there a simpler shortcut that I'm overlooking? I saw this PR and noticed that more work looks to be needed. https://github.com/ariskk/flink/pull/1. How are you able to run things without a full Flink 2.13 build?

Thanks!

**Comment by ariskk** [comment]
Do you have a stacktrace you can share? Also an example `build.sbt`

Starting in 1.15, Scala is completed hidden so you shouldn't face this problem.

**Comment by adschwartz** [comment]
When I go to https://flink.apache.org/downloads.html#apache-flink-1150 

![image](https://user-images.githubusercontent.com/11248996/173675947-e54d43aa-da46-4049-b021-b75de47db15e.png)

It lists two downloads, one is for Flink 1.15.0 for Scala 2.12 and the other is the Source. I don't see any option that is completely free of Scala?

When I start the cluster in standalone mode I also see this entry:
```
2022-06-14 11:45:19,567 INFO  org.apache.flink.runtime.entrypoint.ClusterEntrypoint        [] -  Starting StandaloneSessionClusterEntrypoint (Version: 1.15.0, Scala: 2.12, Rev:3a4c113, Date:2022-04-20T19:50:32+02:00)
```

When I look in the `lib` directory of the zipped bundle I also notice this file `flink-scala_2.12-1.15.0.jar`. Based on this link, it does appear that Flink still comes with default scala support (but I believe it's limited to version 2.12.7): https://mvnrepository.com/artifact/org.apache.flink/flink-streaming-scala_2.12/1.15.0

**Comment by adschwartz** [comment]
Adding my build file:

```
val sharedSettings: Seq[Def.Setting[_]] = Seq(
  version := "0.1.0-SNAPSHOT",
  scalaVersion := "2.13.8",
  fork := true,
  publishArtifact in Test := true,
  test in assembly := {},
  assemblyMergeStrategy in assembly := {
    case PathList("META-INF", xs @ _*) => MergeStrategy.discard
    case x => MergeStrategy.first
  },
  assembly / assemblyOption ~= {
    _.withIncludeScala(false)
  },
)

lazy val root = (project in file("."))
  .settings(
    sharedSettings,
    libraryDependencies ++= Dependencies.core,
    libraryDependencies ++= Dependencies.flinkDependencies,
    assemblyJarName in assembly := "run.jar"
  )
```

```
object Dependencies {

  val catsCoreVersion = "2.7.0"

  val scalaTestVersion = "3.2.11"

  val flinkVersion = "1.15.0"
  val flinkScalaBindingsVersion = "1.15.2"

  val core = Seq(
    "ch.qos.logback" % "logback-classic" % "1.2.11",
  )

  val flinkDependencies = Seq(
    "com.ariskk" % "flink4s_2.13" % flinkScalaBindingsVersion,
    "org.apache.flink" % "flink-clients" % flinkVersion,
  )

  val testDependencies = Seq(
    "org.scalatest" %% "scalatest" % "3.2.11",
  )

}

```

**Comment by adschwartz** [comment]
When I submit the jar manually via the Flink UI I get this error that indicates to me that there's a scala version mismatch:

```
org.apache.flink.runtime.rest.handler.RestHandlerException: Could not execute application. at org.apache.flink.runtime.webmonitor.handlers.JarRunHandler.lambda$handleRequest$1(JarRunHandler.java:113) at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930) at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907) at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705) at java.base/java.lang.Thread.run(Thread.java:829) Caused by: java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'scala.collection.immutable.ArraySeq scala.runtime.ScalaRunTime$.wrapRefArray(java.lang.Object[])' at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702) ... 1 more Caused by: java.lang.NoSuchMethodError: 'scala.collection.immutable.ArraySeq scala.runtime.ScalaRunTime$.wrapRefArray(java.lang.Object[])' at app.tilli.blockchain.asset.TestJob.(TestJob.scala:22) at app.tilli.blockchain.asset.AssetContractReader$.main(AssetContractReader.scala:6) at app.tilli.blockchain.asset.AssetContractRead
```

How are you able to submit your jobs to a standalone flink cluster?

**Comment by adschwartz** [comment]
I now realize that this issue is most likely not related to this repo/work. It's mostly a problem on my end, configuring the standalone cluster correctly. The [release notes](https://nightlies.apache.org/flink/flink-docs-release-1.15/release-notes/flink-1.15/) mention to remove packages related to Scala to achieve the Scala decoupling you mentioned. So I just need to figure out which package is causing me issues and that should solve it. Thanks for helping!

**Comment by adschwartz** [comment]
Confirmed, I had not placed the scala lib jar in the lib folder. Runs fine with that jar. My mistake, thanks!

**Comment by ariskk** [comment]
Nice thanks for reporting back!
